# -*- coding: utf-8 -*-
"""Random Password Generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uDxviIunE77EYjN1y56Od6Wj3EwV9swb
"""

import random
import string

def generate_password(length=12):
    characters = string.ascii_letters + string.digits + string.punctuation
    password = ''.join(random.choice(characters) for i in range(length))
    return password

while(True):
  password_length = input("Enter the desired password length: ")
  if not password_length.isnumeric():
      print("Password length must be a number")
      continue
  else:
    password_length = int(password_length)
    generated_password = generate_password(password_length)
    print(f"Random password generated: {generated_password}")
    break